# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: /Website_2023

# Title of the Site
title: OptiTramp, A l'école de la vie
# Description of the Site
description: A customizable Jekyll portfolio theme
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Vlog, Vélo, Voyage, Ecole
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: antoine-41@live.fr
facebook_username: ElOptitramp
twitter_username: /
instagram_username: antoineoptimum
linkedin_username: antoine-leleu-0ba0676a
github_username:  antoine4790
youtube_channel_id: UCcDP2sVGihbtb5dlYaDd0rg
reddit_username: /
behance_username: antoineleleu
dribbble_username: antoine4790
spotify_username: 112307667

# Google Analytics
google-analytics: 373866055

# Disqus
disqus-shortname: antoineleleu

# Name of the Author
author-name: ElOptitramp
# URL for the Image of the Author
author-image: assets/images/Photo_profil.png
# 60 Words About the Author
author-about: |
  Conscient de la nécessité d'une transition écoresponsable de notre societé vers un modèle plus en accord avec notre environnement , je suis particulièrement intéressé par la manière dont je peux chaque jour trouver comment réduire mes consommations. Ce qui m'a conduit naturellement à me lancer dans le recyclage d'objets (d'abord comme hobby puis en tant que freelance) tels que les smartphones ou tout autre objet multimédia de notre monde aujourd'hui fortement digital. De formation en Bio-informatique, j'ai pu développer des compétences dans des langages tels que C/C++, Java ou encore Javascript. 
  Très intéressé également par les langues étrangères depuis mes derniers voyages à l'étranger, je suis ouvert aux opportunités qui impliqueraient d'utiliser une langue étrangère. 
  Je suis à l'écoute de toute opportunité susceptible de m'apporter l’expérience nécessaire pour mener à terme mes projets professionnels et personnels en utilisant mes compétences informatiques au service de cette transition écoresponsable.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/antoine4790

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
